# Generated by Django 3.1.8 on 2023-12-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='additional_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='operation_type',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Aquisição'), (5, 'Resgate')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Aquisição'), (2, 'Resgate'), (3, 'Interest')]),
        ),
    ]
